server:
  port: 80

spring:
  application:
    name: cloud-order-service
  cloud:
    zookeeper:
      #单机模式
      connect-string: 192.168.81.14:2181
      #集群模式
      #connect-string: 192.168.81.11:2181,192.168.81.12:2181,192.168.81.13:2181