server:
  port: 8001

spring:
  #application:
    #name: cloud-nacos-provider

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    druid:
      validation-query: select 1

  cloud:
    #nacos:
      #discovery:
        #server-addr: localhost:8848 #配置Nacos地址

    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: cloud-eureka-provider-8002

  #spring-cloud-sleuth链路监控
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率值介于 0 到 1 之间，1 则表示全部采集
        probability: 1

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.springcloud.alibaba.entity    # 所有Entity别名类所在包


#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
