server:
  port: 7002

spring:
  application:
    name: cloud-eureka-server

eureka:
  instance:
    #单机配置
    # hostname: localhost
    #集群配置
    hostname: eureka7002.com  #eureka服务端的实例名

  client:
    register-with-eureka: false  #false表示不向注册中心注册自己
    fetch-registry: false  #false表示自己就是注册中心，并不需要去检索服务
    service-url:
      #单机配置
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      #集群配置
      defaultZone: http://eureka7001.com:7001/eureka/  #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。

  server:
    enable-self-preservation: true  #Eureka自我保护机制，默认开启
    eviction-interval-timer-in-ms: 2000  #Eureka服务端剔除服务的时间间隔



